# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.19.2
_src_path: git+https://github.com/oca/oca-addons-repo-template
ci: GitHub
convert_readme_fragments_to_markdown: false
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: false
github_enable_makepot: false
github_enable_stale_action: true
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_test_flavor: Odoo
odoo_version: 10.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: Modules for the Dutch localization
repo_name: Dutch localization
repo_slug: l10n-netherlands
repo_website: https://github.com/OCA/l10n-netherlands

